/**
 * Deterministic explanations.
 *
 * Spec: Master Technical Buildout sections 8.7 and 40. "The product should never force a
 * school administrator to trust a black box. Every material conclusion should have a **Why**
 * button."
 *
 * Two properties matter and they pull in opposite directions.
 *
 * The explanation must be **deterministic** — part of a reproducible result, and never
 * generated by a language model, because a compliance conclusion whose wording drifts
 * between runs cannot be attested to. So rendering is pure substitution: no conditionals, no
 * loops, no expression evaluation. A template cannot compute anything, which means it cannot
 * disagree with the calculation it describes.
 *
 * The explanation must also be **readable by a business officer**, which is why templates are
 * authored as markdown in the rule pack rather than assembled from field names in code. A
 * domain reviewer approving a rule reads the sentence a district will read.
 *
 * When a rule names no template, the fallback renders the calculation steps. That is less
 * fluent and always correct — which is the right way round for a default.
 */

import { formatUsd, amount, isAmountString } from '@complianceos/domain';
import type { CalculationStep, CalculatorValue } from '@complianceos/calculators';

export interface ExplanationContext {
  readonly status: string;
  readonly inputs: Readonly<Record<string, CalculatorValue | null>>;
  readonly output: Readonly<Record<string, CalculatorValue>>;
  readonly steps: readonly CalculationStep[];
  readonly missingInputs: readonly string[];
}

/** Rendered when a placeholder resolves to nothing. Never an empty string, which reads as a typo. */
const ABSENT = '—';

/**
 * Any `{{...}}` span, not only well-formed ones.
 *
 * A narrower pattern leaves an authoring typo — `{{input.prior-local}}`, or someone trying
 * `{{ shortfall + 1 }}` — unmatched and therefore emitted verbatim, so a district reads raw
 * template syntax in a compliance document. Matching everything and rendering the
 * unresolvable ones as the absent marker means template scaffolding can never reach a reader.
 */
const PLACEHOLDER = /\{\{([^{}]*)\}\}/g;

function formatStepValue(step: CalculationStep): string {
  switch (step.unit) {
    case 'USD':
    case 'USD_PER_CHILD':
      return isAmountString(step.value) ? formatUsd(amount(step.value)) : step.value;
    case 'PERCENT':
      return `${step.value}%`;
    default:
      return step.value;
  }
}

/**
 * Walk a dotted path, reading own enumerable properties only.
 *
 * The own-property check is the whole point. Plain indexing walks the prototype chain, so
 * `{{input.constructor}}` and `{{output.toString}}` resolve to members of `Object.prototype`
 * and render as engine internals inside a district-facing compliance explanation. Nothing is
 * ever invoked — a template still cannot compute — but a name that is not a declared input
 * must resolve to nothing at all.
 */
function readPath(source: unknown, path: readonly string[]): unknown {
  let current = source;
  for (const segment of path) {
    if (current === null || current === undefined || typeof current !== 'object') return undefined;
    if (!Object.prototype.hasOwnProperty.call(current, segment)) return undefined;
    current = (current as Record<string, unknown>)[segment];
  }
  return current;
}

function renderValue(value: unknown): string {
  if (value === undefined || value === null) return ABSENT;
  if (Array.isArray(value)) return value.length === 0 ? ABSENT : value.map(renderValue).join(', ');
  if (typeof value === 'object') return JSON.stringify(value);
  if (typeof value === 'string' && isAmountString(value)) return formatUsd(amount(value));
  return String(value);
}

/**
 * Resolve one placeholder.
 *
 * Namespaces are explicit — `input.`, `output.`, `step.` — so a template says where a number
 * came from. `{{ step.required_local }}` reading from the shown work is a stronger guarantee
 * than `{{ required_local }}` reading from wherever it can be found: the sentence and the
 * table below it cannot disagree, because they are the same value.
 */
function resolve(rawPath: string, context: ExplanationContext): string {
  const path = rawPath.trim();
  const segments = path.split('.');
  const [namespace, ...rest] = segments;

  if (namespace === 'status') return context.status;

  if (namespace === 'missing') {
    return context.missingInputs.length === 0 ? ABSENT : context.missingInputs.join(', ');
  }

  if (namespace === 'step') {
    const key = rest.join('.');
    const step = context.steps.find((candidate) => candidate.key === key);
    return step === undefined ? ABSENT : formatStepValue(step);
  }

  if (namespace === 'input') return renderValue(readPath(context.inputs, rest));
  if (namespace === 'output') return renderValue(readPath(context.output, rest));

  return ABSENT;
}

export function renderExplanation(template: string, context: ExplanationContext): string {
  return template.replace(PLACEHOLDER, (_match, path: string) => resolve(path, context)).trim();
}

/**
 * The fallback explanation: the shown work, in order.
 *
 * Used when a rule names a template the pack does not contain. That is a content bug and the
 * pack loader could refuse it — but refusing would mean a district sees nothing at all rather
 * than seeing the arithmetic, and the arithmetic is the part that has to be right.
 */
export function generateExplanation(context: ExplanationContext): string {
  const lines: string[] = [`Result: ${context.status}.`];

  if (context.missingInputs.length > 0) {
    lines.push(
      '',
      'This could not be determined because the following data was not available: ' +
        `${context.missingInputs.join(', ')}.`,
    );
  }

  if (context.steps.length > 0) {
    lines.push('', 'How this was calculated:');
    for (const step of context.steps) {
      const detail = step.detail === undefined ? '' : ` (${step.detail})`;
      const citation = step.citation === undefined ? '' : ` [${step.citation}]`;
      lines.push(`- ${step.label}: ${formatStepValue(step)}${detail}${citation}`);
    }
  }

  return lines.join('\n');
}

/** Render a rule's named template, falling back to the generated step listing. */
export function explain(
  templateName: string,
  templates: ReadonlyMap<string, string>,
  context: ExplanationContext,
): string {
  const template = templates.get(templateName);
  return template === undefined
    ? generateExplanation(context)
    : renderExplanation(template, context);
}
